//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TomaRemedio
{
    using System;
    
    public enum Tipo : int
    {
        SemTarja = 0,
        Amarela = 1,
        Vermelha = 2,
        Preta = 3
    }
}
